version: 2.1
executors:
  unity:
    docker:
      - image: gableroux/unity3d:2019.1.3f1
jobs:
  build-test:
    executor: unity
    steps:
      - checkout
      - run: echo $UNITY_LICENSE | base64 --decode >> .circleci/Unity_License.ulf
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .circleci/Unity_License.ulf || exit 0
      - run: /opt/Unity/Editor/Unity -batchmode -nographics -silent-crashes -logFile -projectPath . -runEditorTests -editorTestsResultFile ./test-results/editMode/results.xml
#      - run: /opt/Unity/Editor/Unity -batchmode -nographics -silent-crashes -noUpm -logFile -projectPath . -runTests -testPlatform playMode -editorTestsResultFile ./test-results/playMode/results.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  version: 2
  build:
    jobs:
      - build-test