version: 2.1
jobs:
  build-test:
    docker:
      - image: gableroux/unity3d:2019.1.14f1
    steps:
      - checkout
      - run: apt -y install xvfb
      - run: echo $UNITY_LICENSE_1_14 | base64 --decode >> .circleci/Unity_License.ulf
      - run: cp -f ./Packages/manifest-linux.json ./Packages/manifest.json
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .circleci/Unity_License.ulf || exit 0
      - run: xvfb-run /opt/Unity/Editor/Unity -batchmode -nographics -silent-crashes -logFile /dev/stdout -projectPath . -runEditorTests -editorTestsResultFile ./test-results/editMode/results.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  android-deploy:
    docker:
      - image: gableroux/unity3d:2019.1.14f1-android
    steps:
      - checkout
      - run: apt -y install xvfb
      - run: echo $UNITY_LICENSE_1_14_ANDROID | base64 --decode >> .circleci/Unity_License.ulf
      - run: cp -f ./Packages/manifest-linux.json ./Packages/manifest.json
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .circleci/Unity_License.ulf || exit 0
      - run: xvfb-run /opt/Unity/Editor/Unity -batchmode -nographics -silent-crashes -quit -executeMethod Editor.Export.ExportAndroidAab
      - store_artifacts:
          path: android-output
workflows:
  version: 2
  build:
    jobs:
      - build-test
      - android-deploy:
          requires:
            - build-test
          filters:
            branches:
              only: master