version: 2.1
executors:
  unity:
    docker:
      - image: gableroux/unity3d:2019.1.3f1
jobs:
  build-test:
    executor: unity
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install libxml2-utils
      - run: echo $UNITY_LICENSE | base64 --decode >> .circleci/Unity_License.ulf
      - run: cp -f ./Packages/manifest-linux.json ./Packages/manifest.json
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .circleci/Unity_License.ulf || exit 0
      - run: /opt/Unity/Editor/Unity -batchmode -nographics -silent-crashes -logFile /dev/stdout -projectPath . -runEditorTests -editorTestsResultFile ./test-results/editMode/results.xml || exit 0
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - run: bash ./testParse.sh
workflows:
  version: 2
  build:
    jobs:
      - build-test